name: "Runner Box"


on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      contents: write
    steps:
    - name: "Check if sender is repository owner"
      if: github.event.repository.owner.login == github.event.sender.login
      run: |
        echo "Sender is the repository owner"
    - name: Not the repository owner
      if: github.event.repository.owner.login != github.event.sender.login
      run: |
        echo "Sender is not the repository owner !"
        exit 1

    - name: "Cleanup"
      uses: rokibhasansagar/slimhub_actions@main

    - name: "Set Swap Space"
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10

    - uses: actions/checkout@v3
    - name: "Setup/Start SSH session"
      uses: mxschmitt/action-tmate@v3.18
      with:
        detached: true

    - name: "Build Kernel"
      run: |
        sudo su
        chmod +x build_kernel.sh
        ./build_kernel.sh

    - name: "Upload Kernel Archive"
      uses: actions/upload-artifact@v4
      with:
        name: 4.19.191_mt6765_dev_prebuilt_kernel
        path: /home/runner/work/Runner-Box/Runner-Box/4.19.191_mt6765_dev.zip
        if-no-files-found: ignore
        retention-days: 7
