name: "Runner Box"


on:
  workflow_dispatch:

jobs:
  deployssh:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check if sender is repository owner
      if: github.event.repository.owner.login == github.event.sender.login
      run: |
        echo "Sender is the repository owner"
    - name: Not the repository owner
      if: github.event.repository.owner.login != github.event.sender.login
      run: |
        echo "Sender is not the repository owner"
        exit 1

    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - uses: actions/checkout@v3
    - name: "Setup/Start SSH session"
      working-directory: /home/runner/work/Runner-Box
      uses: mxschmitt/action-tmate@v3
      with:
        detached: true
